"""Validate node outputs for the NYC FHV dispatch project."""

import argparse
import importlib
import sys
from pathlib import Path
from typing import Callable, Dict, Iterable, List

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _failures_for_missing(paths: Iterable[str]) -> List[str]:
    failures = []
    for relative_path in paths:
        if not (PROJECT_ROOT / relative_path).exists():
            failures.append("missing: {}".format(relative_path))
    return failures


def check_node00() -> List[str]:
    """Check the initialization scaffold only."""
    required_dirs = [
        "configs",
        "data/raw",
        "data/interim",
        "data/processed",
        "data/external",
        "src",
        "scripts",
        "outputs/tables",
        "outputs/figures",
        "outputs/models",
        "outputs/logs",
        "outputs/submission",
        "tests",
    ]
    required_files = [
        "README.md",
        "AGENTS.md",
        "Makefile",
        "requirements.txt",
        ".gitignore",
        "configs/paths.yaml",
        "configs/model.yaml",
        "configs/experiment.yaml",
        "src/__init__.py",
        "src/schema.py",
        "scripts/check_node.py",
        "scripts/run_node.py",
        "pytest.ini",
        "tests/test_schema.py",
    ]

    failures = _failures_for_missing(required_dirs)
    failures.extend(_failures_for_missing(required_files))

    sys.path.insert(0, str(PROJECT_ROOT))
    try:
        importlib.import_module("src")
        importlib.import_module("src.schema")
    except Exception as exc:  # pragma: no cover - reported by CLI.
        failures.append("src import failed: {}".format(exc))

    return failures


def check_not_implemented(node: str) -> List[str]:
    return [
        "{} is not implemented yet. Run nodes sequentially and complete earlier nodes first.".format(
            node
        )
    ]


def check_node01() -> List[str]:
    """Check the raw data audit table generated by Node 01."""
    failures = []
    audit_path = PROJECT_ROOT / "outputs" / "tables" / "node01_data_audit.csv"
    if not audit_path.exists():
        return ["missing: outputs/tables/node01_data_audit.csv"]

    try:
        audit = pd.read_csv(audit_path)
    except Exception as exc:
        return ["could not read audit csv: {}".format(exc)]

    required_columns = [
        "dataset",
        "n_rows",
        "n_cols",
        "columns",
        "missing_rate_summary",
        "datetime_min",
        "datetime_max",
    ]
    missing_columns = [column for column in required_columns if column not in audit.columns]
    if missing_columns:
        failures.append("missing audit columns: {}".format(", ".join(missing_columns)))
        return failures

    required_datasets = {
        "yellow",
        "green",
        "fhv",
        "taxi_zone_lookup",
        "taxi_zones_shp",
    }
    found = set(audit["dataset"].astype(str))
    missing_datasets = required_datasets - found
    if missing_datasets:
        failures.append("missing datasets: {}".format(", ".join(sorted(missing_datasets))))

    for dataset in sorted(required_datasets & found):
        row = audit.loc[audit["dataset"].astype(str) == dataset].iloc[0]
        if int(row["n_rows"]) <= 0:
            failures.append("{} has no rows".format(dataset))
        if int(row["n_cols"]) <= 0:
            failures.append("{} has no columns".format(dataset))
        if not str(row["columns"]).strip():
            failures.append("{} has empty column listing".format(dataset))

    trip_datasets = {"yellow", "green", "fhv"}
    for dataset in sorted(trip_datasets & found):
        row = audit.loc[audit["dataset"].astype(str) == dataset].iloc[0]
        if not str(row["datetime_min"]).strip() or not str(row["datetime_max"]).strip():
            failures.append("{} missing datetime bounds".format(dataset))

    return failures


def check_node02() -> List[str]:
    failures = []
    report_path = PROJECT_ROOT / "outputs" / "tables" / "node02_cleaning_report.csv"
    if not report_path.exists():
        failures.append("missing: outputs/tables/node02_cleaning_report.csv")

    clean_paths = {
        "yellow": PROJECT_ROOT / "data" / "interim" / "yellow_clean.parquet",
        "green": PROJECT_ROOT / "data" / "interim" / "green_clean.parquet",
        "fhv": PROJECT_ROOT / "data" / "interim" / "fhv_clean.parquet",
    }
    for dataset, path in clean_paths.items():
        if not path.exists():
            failures.append("missing: {}".format(path.relative_to(PROJECT_ROOT)))
            continue
        try:
            df = pd.read_parquet(path)
        except Exception as exc:
            failures.append("{} read failed: {}".format(dataset, exc))
            continue
        if df.empty:
            failures.append("{} clean data is empty".format(dataset))
            continue
        if not df["duration_min"].gt(0).all():
            failures.append("{} has non-positive duration".format(dataset))
        if not df["duration_min"].le(180).all():
            failures.append("{} has duration over 180 minutes".format(dataset))
        if not pd.to_datetime(df["pickup_datetime"]).ge("2019-01-01").all():
            failures.append("{} has pickup before 2019-01-01".format(dataset))
        if not pd.to_datetime(df["pickup_datetime"]).lt("2019-02-01").all():
            failures.append("{} has pickup on/after 2019-02-01".format(dataset))
        if dataset in {"yellow", "green"}:
            if not df["trip_distance"].gt(0).all():
                failures.append("{} has non-positive trip distance".format(dataset))
            if not df["total_amount"].gt(0).all():
                failures.append("{} has non-positive total amount".format(dataset))
            if not df["fare_amount"].gt(0).all():
                failures.append("{} has non-positive fare amount".format(dataset))

    return failures


def check_node03() -> List[str]:
    failures = []
    panel_path = PROJECT_ROOT / "data" / "processed" / "hourly_demand_panel.parquet"
    summary_path = PROJECT_ROOT / "outputs" / "tables" / "node03_demand_panel_summary.csv"
    if not panel_path.exists():
        failures.append("missing: data/processed/hourly_demand_panel.parquet")
        return failures
    if not summary_path.exists():
        failures.append("missing: outputs/tables/node03_demand_panel_summary.csv")

    panel = pd.read_parquet(panel_path)
    required = {
        "zone_id",
        "datetime_hour",
        "date",
        "hour",
        "weekday",
        "is_weekend",
        "pickup_count",
        "yellow_count",
        "green_count",
    }
    missing = required - set(panel.columns)
    if missing:
        failures.append("missing panel columns: {}".format(", ".join(sorted(missing))))
        return failures
    if panel["pickup_count"].lt(0).any():
        failures.append("pickup_count has negative values")
    if panel["datetime_hour"].min() != pd.Timestamp("2019-01-01 00:00:00"):
        failures.append("wrong panel start")
    if panel["datetime_hour"].max() != pd.Timestamp("2019-01-31 23:00:00"):
        failures.append("wrong panel end")
    expected_rows = panel["zone_id"].nunique() * 24 * 31
    if len(panel) != expected_rows:
        failures.append("panel is not complete: got {}, expected {}".format(len(panel), expected_rows))
    duplicate_count = panel.duplicated(["zone_id", "datetime_hour"]).sum()
    if duplicate_count:
        failures.append("duplicate zone-hour rows: {}".format(int(duplicate_count)))
    return failures


def check_node04() -> List[str]:
    failures = []
    feature_path = PROJECT_ROOT / "data" / "processed" / "hourly_features.parquet"
    summary_path = PROJECT_ROOT / "outputs" / "tables" / "node04_feature_summary.csv"
    weather_path = PROJECT_ROOT / "data" / "external" / "weather_hourly.csv"
    for path in [feature_path, summary_path, weather_path]:
        if not path.exists():
            failures.append("missing: {}".format(path.relative_to(PROJECT_ROOT)))
    if failures:
        return failures
    features = pd.read_parquet(feature_path)
    required = {
        "temperature",
        "precipitation",
        "snow_indicator",
        "wind_speed",
        "visibility",
        "is_weekend",
        "is_holiday",
        "is_morning_peak",
        "is_evening_peak",
        "is_night",
        "hour_sin",
        "hour_cos",
        "weekday",
        "month",
        "day",
    }
    missing = required - set(features.columns)
    if missing:
        failures.append("missing feature columns: {}".format(", ".join(sorted(missing))))
    key_missing = features[list(required)].isna().mean().max()
    if key_missing > 0:
        failures.append("key feature missing rate is {}".format(key_missing))
    return failures


def check_node05() -> List[str]:
    failures = []
    figure_names = [
        "brooklyn_total_demand_map.png",
        "hourly_pattern.png",
        "weekday_weekend_pattern.png",
        "weather_demand_relation.png",
        "top20_zones.png",
    ]
    for name in figure_names:
        path = PROJECT_ROOT / "outputs" / "figures" / name
        if not path.exists():
            failures.append("missing: outputs/figures/{}".format(name))
        elif path.stat().st_size <= 0:
            failures.append("empty figure: outputs/figures/{}".format(name))
    summary_path = PROJECT_ROOT / "outputs" / "tables" / "node05_eda_summary.csv"
    if not summary_path.exists():
        failures.append("missing: outputs/tables/node05_eda_summary.csv")
    elif pd.read_csv(summary_path).empty:
        failures.append("node05 EDA summary is empty")
    return failures


def check_node06() -> List[str]:
    failures = []
    metrics_path = PROJECT_ROOT / "outputs" / "tables" / "node06_baseline_metrics.csv"
    pred_path = PROJECT_ROOT / "outputs" / "tables" / "node06_baseline_validation_predictions.csv"
    for path in [metrics_path, pred_path]:
        if not path.exists():
            failures.append("missing: {}".format(path.relative_to(PROJECT_ROOT)))
    if failures:
        return failures
    metrics = pd.read_csv(metrics_path)
    required_metrics = {"MAE", "RMSE", "SMAPE"}
    missing = required_metrics - set(metrics.columns)
    if missing:
        failures.append("missing metric columns: {}".format(", ".join(sorted(missing))))
    elif metrics[list(required_metrics)].isna().any().any():
        failures.append("baseline metrics contain missing values")
    if len(metrics) < 3:
        failures.append("expected at least three baselines")
    predictions = pd.read_csv(pred_path)
    if predictions.empty:
        failures.append("validation predictions are empty")
    return failures


def check_node07() -> List[str]:
    failures = []
    metrics_path = PROJECT_ROOT / "outputs" / "tables" / "node07_model_metrics.csv"
    pred_path = PROJECT_ROOT / "outputs" / "tables" / "pred_demand_2019_02_01_hourly.csv"
    fig_path = PROJECT_ROOT / "outputs" / "figures" / "model_validation_compare.png"
    for path in [metrics_path, pred_path, fig_path]:
        if not path.exists():
            failures.append("missing: {}".format(path.relative_to(PROJECT_ROOT)))
    if failures:
        return failures
    pred = pd.read_csv(pred_path, parse_dates=["datetime_hour"])
    if pred["predicted_demand"].lt(0).any():
        failures.append("negative demand prediction")
    hours = pred["datetime_hour"].dt.hour.nunique()
    if hours != 24:
        failures.append("prediction does not cover 24 hours")
    expected_rows = pred["zone_id"].nunique() * 24
    if len(pred) != expected_rows:
        failures.append("prediction row count mismatch")
    if pred[["zone_id", "datetime_hour", "predicted_demand"]].isna().any().any():
        failures.append("prediction has key missing values")
    if fig_path.stat().st_size <= 0:
        failures.append("model validation figure is empty")
    return failures


def check_node08() -> List[str]:
    failures = []
    ref_path = PROJECT_ROOT / "outputs" / "tables" / "od_distance_duration_reference.csv"
    fhv_path = PROJECT_ROOT / "outputs" / "tables" / "fhv_with_estimated_distance.csv"
    for path in [ref_path, fhv_path]:
        if not path.exists():
            failures.append("missing: {}".format(path.relative_to(PROJECT_ROOT)))
    if failures:
        return failures
    ref = pd.read_csv(ref_path)
    fhv = pd.read_csv(fhv_path)
    if ref.empty or fhv.empty:
        failures.append("node08 output is empty")
    if fhv["estimated_distance"].isna().any():
        failures.append("FHV estimated_distance has missing values")
    if not fhv["estimated_distance"].gt(0).all():
        failures.append("FHV estimated_distance must be positive")
    if fhv["estimated_od_duration_min"].isna().any():
        failures.append("FHV estimated_od_duration_min has missing values")
    clean_path = PROJECT_ROOT / "data" / "interim" / "fhv_clean.parquet"
    if clean_path.exists() and len(fhv) != len(pd.read_parquet(clean_path)):
        failures.append("FHV enriched row count does not match clean input")
    return failures


def check_node09() -> List[str]:
    failures = []
    result_path = PROJECT_ROOT / "outputs" / "tables" / "fhv_pricing_results.csv"
    summary_path = PROJECT_ROOT / "outputs" / "tables" / "node09_pricing_model_summary.csv"
    for path in [result_path, summary_path]:
        if not path.exists():
            failures.append("missing: {}".format(path.relative_to(PROJECT_ROOT)))
    if failures:
        return failures
    result = pd.read_csv(result_path)
    required = {"fhv_price", "taxi_reference_price", "estimated_cost", "estimated_profit"}
    missing = required - set(result.columns)
    if missing:
        failures.append("missing pricing columns: {}".format(", ".join(sorted(missing))))
        return failures
    if result[list(required)].isna().any().any():
        failures.append("pricing result has key missing values")
    if not result["fhv_price"].gt(0).all():
        failures.append("fhv_price must be positive")
    fhv_distance = PROJECT_ROOT / "outputs" / "tables" / "fhv_with_estimated_distance.csv"
    if fhv_distance.exists() and len(result) != len(pd.read_csv(fhv_distance)):
        failures.append("pricing row count does not match FHV input")
    return failures


CHECKS: Dict[str, Callable[[], List[str]]] = {
    "node00": check_node00,
    "node01": check_node01,
    "node02": check_node02,
    "node03": check_node03,
    "node04": check_node04,
    "node05": check_node05,
    "node06": check_node06,
    "node07": check_node07,
    "node08": check_node08,
    "node09": check_node09,
}


def run_check(node: str) -> int:
    if node == "all":
        nodes = sorted(CHECKS)
    else:
        nodes = [node]

    all_failures = []
    for current_node in nodes:
        check = CHECKS.get(current_node)
        failures = check() if check else check_not_implemented(current_node)
        if failures:
            all_failures.append((current_node, failures))
        else:
            print("[PASS] {}".format(current_node))

    if all_failures:
        for failed_node, failures in all_failures:
            print("[FAIL] {}".format(failed_node))
            for failure in failures:
                print("  - {}".format(failure))
        return 1

    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate node outputs.")
    parser.add_argument("--node", required=True, help="Node id, for example node00.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    return run_check(args.node.lower())


if __name__ == "__main__":
    raise SystemExit(main())
